name: Test Python

on: [ push, pull_request ]
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12" ]
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Hatch
        run: pipx install hatch --pip-args "click==8.2.1"
      - name: Lint with Hatch (ruff)
        run: hatch run lint
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12" ]
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Hatch
        run: pipx install hatch pytest --pip-args "click==8.2.1"
      - name: Install POCS with Hatch
        run: hatch run pip install -e ".[testing]"
      - name: Test with Hatch
        run: hatch run pytest
      - uses: codecov/codecov-action@v4
        with:
          name: Upload to codecov.io
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
